# Generated by Django 5.1.2 on 2024-10-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo', models.CharField(choices=[('Saf', 'Saf'), ('Horta', 'Horta')], default=None, max_length=12)),
                ('rua', models.CharField(choices=[('Rua1', 'Rua1'), ('Rua2', 'Rua2'), ('Rua3', 'Rua3'), ('Rua4', 'Rua4'), ('Rua5', 'Rua5')], default=None, max_length=12)),
                ('data_colheita', models.DateField(blank=True, null=True)),
                ('data_regada', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
