# Generated by Django 5.1.2 on 2024-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantacao',
            name='rua',
        ),
        migrations.AddField(
            model_name='plantacao',
            name='ruas',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='data_colheita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='data_regada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
