# Generated by Django 5.1.2 on 2024-10-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturas', '0002_remove_plantacao_rua_plantacao_ruas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacao',
            name='ruas',
            field=models.CharField(max_length=255),
        ),
    ]
