# Generated by Django 5.1.2 on 2024-10-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturas', '0003_alter_plantacao_ruas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacao',
            name='ruas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
