# Generated by Django 5.1.2 on 2024-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_user_cpf_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='nome', max_length=50),
        ),
    ]
