# Generated by Django 5.1.2 on 2024-11-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_user_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
