# Generated by Django 5.1.2 on 2024-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('ruas', models.JSONField()),
                ('data_colheita', models.DateField()),
                ('data_regada', models.DateField()),
            ],
        ),
    ]
