# Generated by Django 5.1.2 on 2024-10-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_plantacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plantacao',
        ),
    ]
