# Generated by Django 5.1.2 on 2024-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='conteudo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(max_length=25),
        ),
    ]
