# Generated by Django 5.1.2 on 2024-11-27 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_nota_conteudo_alter_nota_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='titulo',
        ),
        migrations.AddField(
            model_name='nota',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
