# Generated by Django 5.1.2 on 2024-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_remove_nota_titulo_nota_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_criacao',
            field=models.DateTimeField(editable=False),
        ),
    ]
