# Generated by Django 5.1.2 on 2024-11-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_nota_data_atualizacao_alter_nota_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='data_atualizacao',
        ),
    ]
